package igu;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        Descripcion.setVisible(true);
        Divisas.setVisible(false);
        Temperatura.setVisible(false);
        UnMedidas.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Inicio = new javax.swing.JButton();
        UnidadMedidas = new javax.swing.JButton();
        Tempe = new javax.swing.JButton();
        Divisa = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        Descripcion = new javax.swing.JPanel();
        Divisas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        Temperatura = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoGrados = new javax.swing.JTextField();
        selecUnGrados = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        textoConvTemp = new javax.swing.JTextField();
        selecUnConv = new javax.swing.JComboBox<>();
        UnMedidas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Centimetros = new javax.swing.JTextField();
        Metros = new javax.swing.JTextField();
        Yardas = new javax.swing.JTextField();
        Kilometros = new javax.swing.JTextField();
        Millas = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ConvertMedidas = new javax.swing.JTextField();
        SelectMedidas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        UnidadMedidas.setText("Unidades de Medidas");
        UnidadMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadMedidasActionPerformed(evt);
            }
        });

        Tempe.setText("Temperatura");
        Tempe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempeActionPerformed(evt);
            }
        });

        Divisa.setText("Divisas");
        Divisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisaActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Titulo.setText("Por favor elija que es lo que quiere cambiar");

        content.setToolTipText("");
        content.setLayout(new javax.swing.OverlayLayout(content));

        javax.swing.GroupLayout DescripcionLayout = new javax.swing.GroupLayout(Descripcion);
        Descripcion.setLayout(DescripcionLayout);
        DescripcionLayout.setHorizontalGroup(
                DescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 594, Short.MAX_VALUE));
        DescripcionLayout.setVerticalGroup(
                DescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 352, Short.MAX_VALUE));

        content.add(Descripcion);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenidos al sistema de cambio de divisas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("A continuación podra elegir la divisa y el monto a cambiar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija divisa a cambiar", "Dolar",
                "Euros", "Peso Argentino", "Peso Uruguayo", "Guarani", "Bolivianos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Escriba el monto a cambiar separando los sentavos con un punto");

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija divisa final", "Dolar",
                "Euros", "Peso Argentino", "Peso Uruguayo", "Guarani", "Bolivianos" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DivisasLayout = new javax.swing.GroupLayout(Divisas);
        Divisas.setLayout(DivisasLayout);
        DivisasLayout.setHorizontalGroup(
                DivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DivisasLayout.createSequentialGroup()
                                .addGroup(DivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DivisasLayout.createSequentialGroup()
                                                .addContainerGap(221, Short.MAX_VALUE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DivisasLayout.createSequentialGroup()
                                                .addGap(251, 251, 251)
                                                .addComponent(jButton1)))
                                .addGap(223, 223, 223))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DivisasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(DivisasLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(DivisasLayout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3))
                                .addGap(88, 88, 88))
                        .addGroup(DivisasLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(DivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        DivisasLayout.setVerticalGroup(
                DivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DivisasLayout.createSequentialGroup()
                                .addContainerGap(90, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(DivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(17, 17, 17)));

        content.add(Divisas);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Bienvenido al sistema de comparacion de temperaturas");

        jLabel6.setText("Elija entre Celsius, Fahrenheit y Kelvin");

        jLabel7.setText("Ingrese los grados");

        textoGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoGradosKeyTyped(evt);
            }
        });

        selecUnGrados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selecUnGrados
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kevin" }));
        selecUnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecUnGradosActionPerformed(evt);
            }
        });

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        selecUnConv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selecUnConv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kevin" }));
        selecUnConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecUnConvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TemperaturaLayout = new javax.swing.GroupLayout(Temperatura);
        Temperatura.setLayout(TemperaturaLayout);
        TemperaturaLayout.setHorizontalGroup(
                TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TemperaturaLayout.createSequentialGroup()
                                .addContainerGap(102, Short.MAX_VALUE)
                                .addGroup(TemperaturaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                TemperaturaLayout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(92, 92, 92))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                TemperaturaLayout.createSequentialGroup()
                                                        .addComponent(jButton2)
                                                        .addGap(214, 214, 214))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TemperaturaLayout
                                                .createSequentialGroup()
                                                .addGroup(TemperaturaLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(TemperaturaLayout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(48, 48, 48)
                                                                .addComponent(selecUnConv,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(TemperaturaLayout.createSequentialGroup()
                                                                .addGroup(TemperaturaLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(textoConvTemp,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                126,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(TemperaturaLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addGap(40, 40, 40)
                                                                                .addComponent(textoGrados,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        103,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(30, 30, 30)
                                                                .addComponent(selecUnGrados,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(61, 61, 61)))));
        TemperaturaLayout.setVerticalGroup(
                TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TemperaturaLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addGroup(TemperaturaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoGrados, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selecUnGrados, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(TemperaturaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(selecUnConv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(textoConvTemp, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addContainerGap(30, Short.MAX_VALUE)));

        content.add(Temperatura);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 3, 18)); // NOI18N
        jLabel4.setText("Conversor de Medidas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Centimetros");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Yardas");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Kilometros");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Millas");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Metros");

        Clear.setText("Limpiar");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jButton4.setText("Calcular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ConvertMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertMedidasActionPerformed(evt);
            }
        });
        ConvertMedidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ConvertMedidasKeyTyped(evt);
            }
        });

        SelectMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Centimetros", "Metros", "Yardas", "Kilometros", "Millas" }));

        jLabel13.setText("Convertir desde: ");

        javax.swing.GroupLayout UnMedidasLayout = new javax.swing.GroupLayout(UnMedidas);
        UnMedidas.setLayout(UnMedidasLayout);
        UnMedidasLayout.setHorizontalGroup(
                UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ConvertMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SelectMedidas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                .addGap(87, 87, 87)
                                .addGroup(UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                                .addComponent(Clear)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UnMedidasLayout
                                                .createSequentialGroup()
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
                                                        Short.MAX_VALUE)
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                                                .addComponent(Metros,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap())
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                UnMedidasLayout.createSequentialGroup()
                                                                        .addGroup(UnMedidasLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Kilometros,
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        150,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(Millas,
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        150,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(Yardas,
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        150,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(Centimetros,
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        150,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(29, 29, 29)))))));
        UnMedidasLayout.setVerticalGroup(
                UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addGroup(
                                        UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(Centimetros, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(
                                        UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel12)
                                                .addComponent(Metros, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(UnMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UnMedidasLayout.createSequentialGroup()
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(Yardas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(Kilometros,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ConvertMedidas,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(Millas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(UnMedidasLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Clear)
                                                        .addComponent(jButton4)))
                                        .addComponent(SelectMedidas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(28, Short.MAX_VALUE)));

        content.add(UnMedidas);

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
                PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PrincipalLayout.createSequentialGroup()
                                                .addGroup(PrincipalLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(PrincipalLayout.createSequentialGroup()
                                                                .addGap(82, 82, 82)
                                                                .addComponent(Titulo))
                                                        .addGroup(PrincipalLayout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addComponent(Inicio)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Divisa)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Tempe)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(UnidadMedidas)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        PrincipalLayout.setVerticalGroup(
                PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Titulo)
                                .addGap(18, 18, 18)
                                .addGroup(
                                        PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Divisa)
                                                .addComponent(Tempe)
                                                .addComponent(UnidadMedidas)
                                                .addComponent(Inicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        getContentPane().add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivisaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DivisaActionPerformed

        Descripcion.setVisible(false);
        Temperatura.setVisible(false);
        UnMedidas.setVisible(false);
        Divisas.setVisible(true);
    }// GEN-LAST:event_DivisaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed

    }// GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        String valortxt = jTextField1.getText();
        double valor = Double.parseDouble(valortxt);

        int divInit = jComboBox1.getSelectedIndex();
        int divFin = jComboBox2.getSelectedIndex();

        Intercambio intercambio = new Intercambio();
        intercambio.setValor(valor);
        intercambio.setDivFin(divFin);
        intercambio.setDivInit(divInit);

        double resultadofinal = intercambio.convertirDivisa();

        if (divInit == 0 || divFin == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una moneda a ser convertida o convertir");
        } else if (esNum(jTextField1.getText().trim())) {
            JOptionPane.showMessageDialog(null, "El monto convertido es: " + resultadofinal);
        } else {
            JOptionPane.showMessageDialog(null, "No se permite ingresar digitos que no sean numeros");
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyTyped

        char caracter = evt.getKeyChar();

        if (((caracter < '0' || caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.')) {
            evt.consume();
        }
    }// GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed

    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void selecUnGradosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selecUnGradosActionPerformed

    }// GEN-LAST:event_selecUnGradosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        String valorTXTTemp = textoGrados.getText();
        double valorTemp = Double.parseDouble(valorTXTTemp);

        int tempInit = selecUnGrados.getSelectedIndex();
        int tempFin = selecUnConv.getSelectedIndex();

        Intercambio intercambioTemp = new Intercambio();
        intercambioTemp.setValorTemp(valorTemp);
        intercambioTemp.setTempInit(tempInit);
        intercambioTemp.setTempFin(tempFin);

        double resultFinalTemp = intercambioTemp.convertirTemp();
        String resultFinalTempString = String.valueOf(resultFinalTemp);

        textoConvTemp.setText(resultFinalTempString);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void textoGradosKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textoGradosKeyTyped

        char caracter = evt.getKeyChar();

        if (((caracter < '0' || caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.')) {
            evt.consume();
        }
    }// GEN-LAST:event_textoGradosKeyTyped

    private void TempeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TempeActionPerformed

        Descripcion.setVisible(false);
        Temperatura.setVisible(true);
        Divisas.setVisible(false);
        UnMedidas.setVisible(false);

    }// GEN-LAST:event_TempeActionPerformed

    private void UnidadMedidasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UnidadMedidasActionPerformed

        Descripcion.setVisible(false);
        Temperatura.setVisible(false);
        Divisas.setVisible(false);
        UnMedidas.setVisible(true);
    }// GEN-LAST:event_UnidadMedidasActionPerformed

    private void selecUnConvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selecUnConvActionPerformed

    }// GEN-LAST:event_selecUnConvActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InicioActionPerformed

        Descripcion.setVisible(true);
        Temperatura.setVisible(false);
        Divisas.setVisible(false);
        UnMedidas.setVisible(false);
    }// GEN-LAST:event_InicioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed

        double ConverMedidas = Double.parseDouble(ConvertMedidas.getText());

        int selecMedidas = SelectMedidas.getSelectedIndex();

        switch (selecMedidas) {
            case 0 -> {
                String Cent = String.valueOf(ConverMedidas);
                double Metro = ConverMedidas / 100;
                String Met = String.valueOf(Metro);
                double yard = ConverMedidas / 91.44;
                String Yard = String.valueOf(yard);
                double km = ConverMedidas / 100000;
                String Km = String.valueOf(km);
                double mill = ConverMedidas / 160900;
                String Mill = String.valueOf(mill);
                Centimetros.setText(Cent);
                Metros.setText(Met);
                Yardas.setText(Yard);
                Kilometros.setText(Km);
                Millas.setText(Mill);
            }
            case 1 -> {
                double cent = ConverMedidas * 100;
                String Cent = String.valueOf(cent);
                String Met = String.valueOf(ConverMedidas);
                double yard = ConverMedidas * 1.09361;
                String Yard = String.valueOf(yard);
                double km = ConverMedidas / 1000;
                String Km = String.valueOf(km);
                double mill = ConverMedidas / 1609;
                String Mill = String.valueOf(mill);
                Centimetros.setText(Cent);
                Metros.setText(Met);
                Yardas.setText(Yard);
                Kilometros.setText(Km);
                Millas.setText(Mill);
            }
            case 2 -> {
                double cent = ConverMedidas * 91.44;
                String Cent = String.valueOf(cent);
                double met = ConverMedidas / 1.09361;
                String Met = String.valueOf(met);
                String Yard = String.valueOf(ConverMedidas);
                double km = ConverMedidas / 1094;
                String Km = String.valueOf(km);
                double mill = ConverMedidas / 1760;
                String Mill = String.valueOf(mill);
                Centimetros.setText(Cent);
                Metros.setText(Met);
                Yardas.setText(Yard);
                Kilometros.setText(Km);
                Millas.setText(Mill);
            }
            case 3 -> {
                double cent = ConverMedidas * 100000;
                String Cent = String.valueOf(cent);
                double met = ConverMedidas * 1000;
                String Met = String.valueOf(met);
                double yard = ConverMedidas * 1093.61;
                String Yard = String.valueOf(yard);
                String Km = String.valueOf(ConverMedidas);
                double mill = ConverMedidas / 1.609;
                String Mill = String.valueOf(mill);
                Centimetros.setText(Cent);
                Metros.setText(Met);
                Yardas.setText(Yard);
                Kilometros.setText(Km);
                Millas.setText(Mill);
            }
            default -> {
                double cent = ConverMedidas * 160934;
                String Cent = String.valueOf(cent);
                double met = ConverMedidas * 1609.34;
                String Met = String.valueOf(met);
                double yard = ConverMedidas * 1760;
                String Yard = String.valueOf(yard);
                double km = ConverMedidas * 1.60934;
                String Km = String.valueOf(km);
                String Mill = String.valueOf(ConverMedidas);
                Centimetros.setText(Cent);
                Metros.setText(Met);
                Yardas.setText(Yard);
                Kilometros.setText(Km);
                Millas.setText(Mill);
            }
        }
    }// GEN-LAST:event_jButton4ActionPerformed

    private void ConvertMedidasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConvertMedidasActionPerformed

    }// GEN-LAST:event_ConvertMedidasActionPerformed

    private void ConvertMedidasKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_ConvertMedidasKeyTyped

        char caracter = evt.getKeyChar();

        if (((caracter < '0' || caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.')) {
            evt.consume();
        }
    }// GEN-LAST:event_ConvertMedidasKeyTyped

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ClearActionPerformed

        Centimetros.setText("");
        Metros.setText("");
        Yardas.setText("");
        Kilometros.setText("");
        Millas.setText("");
    }// GEN-LAST:event_ClearActionPerformed

    public boolean esNum(String cadena) {
        try {
            Float.parseFloat(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Centimetros;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField ConvertMedidas;
    private javax.swing.JPanel Descripcion;
    private javax.swing.JButton Divisa;
    private javax.swing.JPanel Divisas;
    private javax.swing.JButton Inicio;
    private javax.swing.JTextField Kilometros;
    private javax.swing.JTextField Metros;
    private javax.swing.JTextField Millas;
    private javax.swing.JPanel Principal;
    private javax.swing.JComboBox<String> SelectMedidas;
    private javax.swing.JButton Tempe;
    private javax.swing.JPanel Temperatura;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel UnMedidas;
    private javax.swing.JButton UnidadMedidas;
    private javax.swing.JTextField Yardas;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> selecUnConv;
    private javax.swing.JComboBox<String> selecUnGrados;
    private javax.swing.JTextField textoConvTemp;
    private javax.swing.JTextField textoGrados;
    // End of variables declaration//GEN-END:variables
}
